proxy:
  image:
    name: docker.io/library/nginx
    tag: 1.25.1
  ports:
    container: 80
    host: 8080
  container:
    name: registry-proxy
  config:
    readOnly: true
    mountPath: /etc/nginx/templates
  resources:
    cpu:
      request: 100m
      limit: 250m
    memory:
      request: 64Mi
      limit: 256Mi

registry:
  image:
    name: docker.io/mcronce/oci-registry
    tag: v0.3.9
  container:
    name: oci-registry
  storage:
    mountPath: /data
  port: 5000
  resources:
    cpu:
      request: 250m
      limit: 2000m
    memory:
      request: 128Mi
      limit: 512Mi

hostname: &hostname registry.studiop
user: core
storage:
  files:
    template:
      - path: /etc/zincati/config.d/51-rollout-wariness.toml
        contents: files/zincati-rollout.toml
      - path: /etc/zincati/config.d/55-updates-strategy.toml
        contents: files/zincati-reboot.toml
    inline:
      - path: /etc/sysctl.d/20-silence-audit.conf
        contents: kernel.printk=4
      - path: /etc/hostname
        contents: *hostname
      - path: /var/lib/systemd/linger/core
        mode: 0644
  folders:
    - path: /home/core/.config
    - path: /home/core/.config/systemd
    - path: /home/core/.config/systemd/user
    - path: /home/core/.config/systemd/user/default.target.wants
  links:
    - path: /home/core/.config/systemd/user/default.target.wants/podman.socket
      target: /usr/lib/systemd/user/podman.socket
systemd:
  units:
    - name: sshd.service
    - name: serial-getty@ttyAMA0.service
    - name: docker.service
      enabled: 'false'
    - name: rpm-ostree-countme.service
      enabled: 'false'
    - name: rpm-ostree-countme.timer
      enabled: 'false'
update:
  wariness: 0.5
  window:
    length: 60
    start: 1:00
    days:
      - Sun
butane:
  version: 1.5.0
defaults:
  systemd:
    enabled: true