inputFiles:
  - templates/butane.tpl
execPipe: true
postExec:
  - butane
  - --pretty
  - --output
  - ignition.json

context:
  Values:
    url: merge:values.yaml|../global.yaml

templates:
  - systemd=templates/systemd/
  - files=templates/files/