inputFiles:
  - templates/butane.tpl
execPipe: true
postExec:
  - butane
  - --pretty
  - --output
  - ignition.json

context:
  Values:
    url: merge:values.yaml|../global/values.yaml

templates:
  - files=templates/files/
  - global=../global/templates/