inputFiles:
  - templates/2u.yml.tmpl
execPipe: true
postExec:
  - ct
  - --pretty
  - --out-file
  - ignition.json
context:
  values:
    url: values.yaml
  global:
    url: ../global.yaml

templates:
  - systemd=templates/systemd/
  - files=templates/files/