inputFiles:
  - templates/config.tpl
execPipe: true
postExec:
  - ct
  - --pretty
  - --out-file
  - ignition.json
context:
  Values:
    url: merge:values.yaml|../global.yaml

templates:
  - systemd=templates/systemd/
  - files=templates/files/