hostname: &hostname coreos
docker:
  compose:
    path: &compose-path /opt/bin/docker-compose
    stacks:
      portainer: &portainer-file /opt/docker-compose/portainer.yml

systemd:
  units:
    - name: docker.service
    - name: serial-getty@ttyS0.service
    - name: portainer.service
      contents: global/portainer.service
    - name: reboot.timer
      contents: global/reboot.timer
    - name: reboot.service
      contents: global/reboot.service
      enabled: 'false'
    - name: rpm-ostree-countme.service
      enabled: 'false'

storage:
  label: &docker-label docker
  disks:
    - device: &docker1 ata-Samsung_SSD_850_EVO_500GB_S21HNXBG538814W
      partitions:
        - label: *docker-label
    - device: &docker2 ata-Samsung_SSD_850_EVO_500GB_S2RANB0J507595K
      partitions:
        - label: *docker-label
  raid:
    - name: *docker-label
      level: mirror
      disks:
        - *docker1
        - *docker2
  filesystems:
    - path: /var/lib/docker
      device: /dev/md/docker
      label: *docker-label
  files:
    remote:
      - path: *portainer-file
        url: https://raw.githubusercontent.com/studioph/compose/master/portainer.yml
      - path: *compose-path
        mode: 0755
        url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64
    template:
      - path: /etc/selinux/config
        mode: 0600
        overwrite: true
        contents: global/selinux.config
      - path: /etc/NetworkManager/system-connections/1g.nmconnection
        mode: 0600
        contents: global/static.nmconnection
      - path: /etc/NetworkManager/system-connections/10g.nmconnection
        mode: 0600
        contents: files/10g.nmconnection
    inline:
      - path: /etc/sysctl.d/20-silence-audit.conf
        contents: kernel.printk=4
      - path: /etc/hostname
        contents: *hostname

network:
  g1:
    ip: 10.0.1.3/24
    mac: 18:c0:4d:e0:80:28
  g10:
    ip: 10.0.10.3/24
    mac: e4:1d:2d:7e:f4:c0