disks:
  ssd1: ata-Samsung_SSD_850_EVO_500GB_S21HNXBG538814W
  ssd2: ata-Samsung_SSD_850_EVO_500GB_S2RANB0J507595K
docker:
  compose:
    dir: /home/core
    version: v2.4.1
  user: core
raid:
  name: docker
wipe:
  partition: true
  filesystem: false
network:
  g1:
    ip: 10.0.1.3/24
    mac: 18:c0:4d:e0:80:28
  g10:
    ip: 10.0.10.3/24
    mac: e4:1d:2d:7e:f4:c0
kmods:
  overlay:
    upper: /opt/overlay/modules
    lower: /usr/lib/modules