hostname: &hostname iaas
docker:
  compose:
    path: &compose-path /opt/bin/docker-compose
    stacks:
      portainer: &portainer-file /opt/docker-compose/portainer.yml

network:
  g1:
    mac: dc:a6:32:5b:ac:1b
    ip: 10.0.1.10

systemd:
  units:
    - name: docker.service
    - name: serial-getty@ttyAMA0.service
    - name: portainer.service
      contents: global/portainer.service

storage:
  files:
    remote:
      - path: *portainer-file
        url: https://raw.githubusercontent.com/paulhutchings/compose/master/portainer.yml
      - path: *compose-path
        mode: 0755
        url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-aarch64
    template:
      - path: /etc/selinux/config
        mode: 0600
        overwrite: true
        contents: global/selinux.config
      - path: /etc/NetworkManager/system-connections/1g.nmconnection
        mode: 0600
        contents: global/static.nmconnection
      - path: /etc/zincati/config.d/51-rollout-wariness.toml
        contents: files/zincati-rollout.toml
      - path: /etc/zincati/config.d/55-updates-strategy.toml
        contents: files/zincati-reboot.toml
    inline:
      - path: /etc/sysctl.d/20-silence-audit.conf
        contents: kernel.printk=4
      - path: /etc/hostname
        contents: *hostname

update:
  wariness: 0.5
  window:
    length: 60
    start: 1:00
    days:
      - Sun